name: Jenkins Pipeline in GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jenkins-pipeline:
    runs-on: ubuntu-latest  # Uses GitHub-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Jenkins in Docker
        run: |
          docker run -d --name jenkins -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts
          sleep 60  # Increased wait time for Jenkins to start

      - name: Verify Jenkins is Running
        run: docker ps -a  # Lists running containers for debugging

      - name: Run Jenkins Pipeline
        run: |
          docker exec jenkins bash -c "jenkins-cli build my-pipeline || echo 'Jenkins pipeline execution failed.'"
